# Generated by Django 5.0.7 on 2024-08-05 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_map', '0002_location_created_at_location_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_details',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=40)),
                ('phone_number', models.CharField(max_length=10)),
                ('job_title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
