# Generated by Django 5.0.7 on 2024-08-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_map', '0003_employee_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee_details',
        ),
    ]
