# Generated by Django 5.0.7 on 2024-08-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
