# Generated by Django 5.0.7 on 2024-08-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0003_alter_location_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
