# Generated by Django 5.0.7 on 2024-08-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0004_alter_location_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
